package com.opsnexus.analytics;
import com.opsnexus.assistant.DeepSeekChat;import com.opsnexus.governance.AiGovernanceService;import com.opsnexus.knowledge.KnowledgeException;
import java.sql.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.*;import org.springframework.jdbc.support.GeneratedKeyHolder;import org.springframework.stereotype.Service;
@Service public class AnalyticsService{
 private static final String SCHEMA="You generate exactly one H2 SELECT statement and no explanation. Allowed tables/columns: service_catalog(id,service_name,display_name,owner_name,current_version,runtime_status); release_record(id,service_name,version_no,environment,status,released_at,summary); incident_record(id,service_name,symptom,root_cause,resolution,status,occurred_at,resolved_at). Allowed functions: COUNT,SUM,AVG,MIN,MAX,DATEADD. No SELECT *, CTE, UNION, subquery, system table or more than two JOINs. Join only on equal service_name. Use aliases only from selected expressions.";
 private final JdbcTemplate audit;private final DeepSeekChat ai;private final SqlSafetyValidator validator;private final AiGovernanceService governance;private final String url,user,password;
 public AnalyticsService(JdbcTemplate audit,DeepSeekChat ai,SqlSafetyValidator validator,AiGovernanceService governance,@Value("${ops.analytics-url}")String url,@Value("${ops.analytics-username}")String user,@Value("${ops.analytics-password}")String password){this.audit=audit;this.ai=ai;this.validator=validator;this.governance=governance;this.url=url;this.user=user;this.password=password;}
 public Map<String,Object> query(long userId,String question){if(question==null||question.isBlank()||question.length()>300)throw new KnowledgeException(400,"INVALID_INPUT","分析问题不能为空且不能超过 300 字");String requestId=UUID.randomUUID().toString(),sql=null;long auditId=createAudit(requestId,userId,question),started=System.nanoTime();
  try{var permit=governance.enter(userId,"TEXT_TO_SQL",ai.modelName(),question.length());try{sql=ai.complete(SCHEMA,question);permit.output(sql.length());}catch(Exception e){permit.fail("SQL_GENERATION_FAILED");throw e;}finally{permit.close();}String safe=validator.validate(sql);audit.update("UPDATE sql_query_audit SET generated_sql=?,validation_status='PASSED' WHERE id=?",safe,auditId);var result=execute(safe);long ms=(System.nanoTime()-started)/1_000_000;audit.update("UPDATE sql_query_audit SET execution_status='SUCCESS',latency_ms=?,row_count=? WHERE id=?",ms,result.rows.size(),auditId);return Map.of("auditId",auditId,"generatedSql",safe,"columns",result.columns,"rows",result.rows,"rowCount",result.rows.size(),"summary",summarize(result.rows));}
  catch(Exception e){String reason=e instanceof KnowledgeException?e.getMessage():"查询生成或执行失败";audit.update("UPDATE sql_query_audit SET generated_sql=?,validation_status=CASE WHEN validation_status='PENDING' THEN 'REJECTED' ELSE validation_status END,execution_status='FAILED',latency_ms=?,failure_reason=? WHERE id=?",sql,(System.nanoTime()-started)/1_000_000,reason,auditId);if(e instanceof KnowledgeException k)throw k;throw new KnowledgeException(503,"ANALYTICS_FAILED",reason);}}
 public List<Map<String,Object>> audits(){return audit.queryForList("SELECT id,request_id,user_id,question,generated_sql,validation_status,execution_status,latency_ms,row_count,failure_reason,created_at FROM sql_query_audit ORDER BY id DESC LIMIT 30");}
 private long createAudit(String requestId,long userId,String question){try{var kh=new GeneratedKeyHolder();audit.update(c->{var p=c.prepareStatement("INSERT INTO sql_query_audit(request_id,user_id,question,validation_status,execution_status) VALUES(?,?,?,'PENDING','NOT_STARTED')",new String[]{"ID"});p.setString(1,requestId);p.setLong(2,userId);p.setString(3,question);return p;},kh);return Objects.requireNonNull(kh.getKey()).longValue();}catch(Exception e){throw new KnowledgeException(503,"AUDIT_UNAVAILABLE","审计不可用，已拒绝执行查询");}}
 private Result execute(String sql)throws SQLException{try(Connection c=DriverManager.getConnection(readOnlyUrl(),user,password)){c.setReadOnly(true);try(Statement s=c.createStatement()){s.setMaxRows(100);s.setQueryTimeout(3);try(ResultSet rs=s.executeQuery(sql)){var md=rs.getMetaData();var columns=new ArrayList<String>();for(int i=1;i<=md.getColumnCount();i++)columns.add(md.getColumnLabel(i));var rows=new ArrayList<Map<String,Object>>();while(rs.next()){var row=new LinkedHashMap<String,Object>();for(int i=1;i<=md.getColumnCount();i++)row.put(columns.get(i-1),rs.getObject(i));rows.add(row);}return new Result(columns,rows);}}}}
 private String readOnlyUrl(){return url.startsWith("jdbc:h2:")?url.replaceAll(";DB_CLOSE_DELAY=[^;]*","").replaceAll(";DB_CLOSE_ON_EXIT=[^;]*",""):url;}
 private String summarize(List<Map<String,Object>> rows){return rows.isEmpty()?"查询成功，但没有符合条件的记录。":"安全查询成功，共返回 "+rows.size()+" 行；结论仅基于页面展示的数据。";}
 private record Result(List<String> columns,List<Map<String,Object>> rows){}
}
