package com.opsnexus.governance;
import com.opsnexus.knowledge.KnowledgeException;import java.time.Duration;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;import org.springframework.beans.factory.annotation.Value;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.data.redis.core.script.DefaultRedisScript;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
@Service public class AiGovernanceService{
 private static final DefaultRedisScript<Long> UNLOCK=new DefaultRedisScript<>("if redis.call('get',KEYS[1])==ARGV[1] then return redis.call('del',KEYS[1]) else return 0 end",Long.class);
 private final JdbcTemplate db;private final StringRedisTemplate redis;private final int perMinute;private final ConcurrentMap<Long,Deque<Long>> windows=new ConcurrentHashMap<>();private final Set<Long> active=ConcurrentHashMap.newKeySet();private volatile String limiterBackend="MEMORY";
 public AiGovernanceService(JdbcTemplate db,StringRedisTemplate redis,@Value("${ops.ai-rate-per-minute:10}")int perMinute){this.db=db;this.redis=redis;this.perMinute=perMinute;}
 public Permit enter(long user,String scene,String model,int inputChars){try{return enterRedis(user,scene,model,inputChars);}catch(KnowledgeException e){throw e;}catch(Exception ignored){limiterBackend="MEMORY";return enterMemory(user,scene,model,inputChars);}}
 private Permit enterRedis(long user,String scene,String model,int inputChars){String token=UUID.randomUUID().toString(),lock="opsnexus:ai:active:"+user;Boolean acquired=redis.opsForValue().setIfAbsent(lock,token,Duration.ofSeconds(70));if(!Boolean.TRUE.equals(acquired))throw new KnowledgeException(429,"AI_BUSY","当前已有生成任务，请等待完成");try{String rate="opsnexus:ai:rate:"+user+":"+(System.currentTimeMillis()/60_000);Long count=redis.opsForValue().increment(rate);if(count!=null&&count==1)redis.expire(rate,Duration.ofSeconds(90));if(count==null||count>perMinute){unlock(lock,token);throw new KnowledgeException(429,"AI_RATE_LIMITED","AI 请求过于频繁，请稍后再试");}limiterBackend="REDIS";return new Permit(user,scene,model,inputChars,true,lock,token);}catch(KnowledgeException e){throw e;}catch(Exception e){unlockQuietly(lock,token);throw e;}}
 private Permit enterMemory(long user,String scene,String model,int inputChars){long now=System.currentTimeMillis();var q=windows.computeIfAbsent(user,k->new ArrayDeque<>());synchronized(q){while(!q.isEmpty()&&q.peekFirst()<now-60_000)q.removeFirst();if(q.size()>=perMinute)throw new KnowledgeException(429,"AI_RATE_LIMITED","AI 请求过于频繁，请稍后再试");if(!active.add(user))throw new KnowledgeException(429,"AI_BUSY","当前已有生成任务，请等待完成");q.addLast(now);}return new Permit(user,scene,model,inputChars,false,null,null);}
 public String limiterBackend(){try{redis.hasKey("opsnexus:ai:status");return "REDIS";}catch(Exception ignored){return "MEMORY";}}
 public List<Map<String,Object>> recent(){return db.queryForList("SELECT id,request_id,user_id,scene,model_name,latency_ms,input_tokens,output_tokens,token_estimated,status,error_code,created_at FROM ai_call_log ORDER BY id DESC LIMIT 50");}
 private void unlock(String key,String token){redis.execute(UNLOCK,List.of(key),token);}private void unlockQuietly(String key,String token){try{unlock(key,token);}catch(Exception ignored){}}
 public final class Permit implements AutoCloseable{private final long user,started=System.nanoTime();private final String requestId=UUID.randomUUID().toString(),scene,model,lockKey,lockToken;private final int inputChars;private final boolean redisLock;private int outputChars;private String status="SUCCESS",errorCode;private final AtomicBoolean closed=new AtomicBoolean();private Permit(long user,String scene,String model,int inputChars,boolean redisLock,String lockKey,String lockToken){this.user=user;this.scene=scene;this.model=model;this.inputChars=inputChars;this.redisLock=redisLock;this.lockKey=lockKey;this.lockToken=lockToken;}public void output(int chars){outputChars+=Math.max(0,chars);}public void fail(String code){status="FAILED";errorCode=code;}@Override public void close(){if(!closed.compareAndSet(false,true))return;if(redisLock)unlockQuietly(lockKey,lockToken);else active.remove(user);db.update("INSERT INTO ai_call_log(request_id,user_id,scene,model_name,latency_ms,input_tokens,output_tokens,token_estimated,status,error_code) VALUES(?,?,?,?,?,?,?,?,?,?)",requestId,user,scene,model,(System.nanoTime()-started)/1_000_000,estimate(inputChars),estimate(outputChars),true,status,errorCode);}}
 private int estimate(int chars){return chars==0?0:Math.max(1,(int)Math.ceil(chars/4.0));}
}
