package com.opsnexus.assistant;
import com.opsnexus.knowledge.KnowledgeException;import java.util.*;import org.springframework.ai.tool.annotation.Tool;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
@Service public class BusinessToolService{
 private final JdbcTemplate db;public BusinessToolService(JdbcTemplate db){this.db=db;}
 @Tool(description="查询白名单服务的负责人、当前版本和演示运行状态") public List<Map<String,Object>> serviceInfo(String service){requireService(service);return db.queryForList("SELECT service_name,display_name,owner_name,current_version,runtime_status FROM service_catalog WHERE service_name=?",service);}
 @Tool(description="查询白名单服务最近五条发布记录") public List<Map<String,Object>> latestReleases(String service){requireService(service);return db.queryForList("SELECT version_no,environment,status,released_at,summary FROM release_record WHERE service_name=? ORDER BY released_at DESC LIMIT 5",service);}
 @Tool(description="查询白名单服务最近五条历史故障记录") public List<Map<String,Object>> recentIncidents(String service){requireService(service);return db.queryForList("SELECT symptom,root_cause,resolution,status,occurred_at FROM incident_record WHERE service_name=? ORDER BY occurred_at DESC LIMIT 5",service);}
 public Map<String,Object> query(long user,String question){if(question==null||question.isBlank()||question.length()>300)throw new KnowledgeException(400,"INVALID_INPUT","查询不能为空且不能超过 300 字");String service=db.queryForList("SELECT service_name FROM service_catalog",String.class).stream().filter(question::contains).findFirst().orElseThrow(()->new KnowledgeException(400,"SERVICE_REQUIRED","请在问题中写明服务名称，例如 order-service"));String tool;if(question.matches(".*(发布|上线|回滚|版本记录).*"))tool="latest_releases";else if(question.matches(".*(故障|事故|异常|根因|历史).*"))tool="recent_incidents";else tool="service_info";List<Map<String,Object>> rows;try{rows=switch(tool){case"latest_releases"->latestReleases(service);case"recent_incidents"->recentIncidents(service);default->serviceInfo(service);};db.update("INSERT INTO tool_call_audit(user_id,tool_name,parameter_summary,result_count,success) VALUES(?,?,?,?,TRUE)",user,tool,"service="+service,rows.size());}catch(Exception e){db.update("INSERT INTO tool_call_audit(user_id,tool_name,parameter_summary,result_count,success) VALUES(?,?,?,?,FALSE)",user,tool,"service="+service,0);throw e;}return Map.of("toolName",tool,"serviceName",service,"parameters",Map.of("service",service),"rows",rows,"resultCount",rows.size(),"explanation",explain(tool,service,rows));}
 private String explain(String tool,String service,List<Map<String,Object>> rows){if(rows.isEmpty())return service+" 暂无相关记录。";return switch(tool){case"latest_releases"->service+" 最近共有 "+rows.size()+" 条发布记录，最新版本为 "+rows.getFirst().get("VERSION_NO")+"，状态 "+rows.getFirst().get("STATUS")+"。";case"recent_incidents"->service+" 查询到 "+rows.size()+" 条历史故障，可展开查看根因与处理办法。";default->service+" 当前版本为 "+rows.getFirst().get("CURRENT_VERSION")+"，负责人 "+rows.getFirst().get("OWNER_NAME")+"。";};}
 private void requireService(String service){if(db.queryForObject("SELECT COUNT(*) FROM service_catalog WHERE service_name=?",Integer.class,service)==0)throw new KnowledgeException(404,"SERVICE_NOT_FOUND","服务不存在");}
}
