<script setup lang="ts">
import{ref,onMounted}from'vue';
type Item=Record<string,any>;const services=ref<Item[]>([]),bases=ref<Item[]>([]),history=ref<Item[]>([]),service=ref('order-service'),kbId=ref(0),symptom=ref(''),context=ref(''),result=ref(''),evidence=ref<Item|null>(null),diagnosisId=ref(0),busy=ref(false),error=ref('');const token=()=>sessionStorage.getItem('ops-token')||'';
async function api(path:string,options:RequestInit={}){const r=await fetch('/api'+path,{...options,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json',...options.headers}}),b=await r.json();if(!r.ok)throw Error(b.message);return b.data}
async function loadHistory(){history.value=await api('/assistant/diagnosis/history')}async function resolve(id:number){await api('/assistant/diagnosis/'+id+'/resolve',{method:'PATCH'});await loadHistory()}
async function diagnose(){if(!symptom.value.trim())return;busy.value=true;result.value='';evidence.value=null;diagnosisId.value=0;error.value='';try{const r=await fetch('/api/assistant/diagnose/stream',{method:'POST',headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:JSON.stringify({kbId:kbId.value,serviceName:service.value,symptom:symptom.value,context:context.value})}),reader=r.body?.getReader();if(!reader)throw Error('无法读取诊断响应');const decoder=new TextDecoder();let buffer='';while(true){const{done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const blocks=buffer.split(/\r?\n\r?\n/);buffer=blocks.pop()||'';for(const block of blocks){let event='',data='';for(const line of block.split(/\r?\n/)){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim()}if(!data)continue;const p=JSON.parse(data);if(event==='delta')result.value+=p.content;if(event==='evidence'){evidence.value=p;diagnosisId.value=p.diagnosisId}if(event==='error')throw Error(p.message)}if(done)break}await loadHistory()}catch(e){error.value=e instanceof Error?e.message:'诊断失败'}finally{busy.value=false}}
onMounted(async()=>{try{[services.value,bases.value,history.value]=await Promise.all([api('/assistant/diagnosis/services'),api('/knowledge-bases'),api('/assistant/diagnosis/history')]);if(bases.value.length)kbId.value=bases.value[0].id}catch(e){error.value=e instanceof Error?e.message:'加载失败'}});
</script>
<template><section><div class="assistant-head"><div><span class="eyebrow">GUIDED TROUBLESHOOTING</span><h1>故障辅助诊断</h1><p class="muted">组合服务状态、发布记录、历史故障与 SOP，生成可核验的排查路径。</p></div></div><div class="diagnosis-grid"><div><form class="diagnosis-form" @submit.prevent="diagnose"><label>目标服务<select v-model="service"><option v-for="s in services" :key="s.SERVICE_NAME" :value="s.SERVICE_NAME">{{s.DISPLAY_NAME}} · {{s.CURRENT_VERSION}}</option></select></label><label>知识库<select v-model="kbId"><option v-for="b in bases" :key="b.id" :value="b.id">{{b.name}}</option></select></label><label>故障现象<textarea v-model="symptom" required rows="4" placeholder="例如：接口延迟升高，日志出现 Redis 获取连接超时"/></label><label>错误日志与上下文<textarea v-model="context" rows="5" placeholder="发生时间、影响范围、关键日志、最近变更等"/></label><p v-if="error" class="banner error">{{error}}</p><button :disabled="busy||!symptom.trim()">{{busy?'正在组合证据并分析…':'开始诊断'}}</button></form><div class="diagnosis-history"><b>最近诊断</b><p v-if="!history.length" class="muted">暂无记录</p><article v-for="h in history" :key="h.ID"><div><strong>{{h.SERVICE_NAME}}</strong><small>{{h.SYMPTOM}}</small></div><button v-if="h.STATUS==='OPEN'" class="outline" @click="resolve(h.ID)">标记解决</button><span v-else>已解决</span></article></div></div><div class="diagnosis-result"><div v-if="!result" class="empty"><div class="large-icon">⌁</div><h3>等待诊断信息</h3><p>系统只提供辅助判断，不会执行真实运维命令。</p></div><template v-else><div class="result-title"><b>诊断报告 #{{diagnosisId}}</b><span>待人工确认</span></div><pre>{{result}}</pre><div v-if="evidence" class="evidence-summary"><b>诊断证据快照</b><p>服务版本：{{evidence.toolEvidence?.service?.CURRENT_VERSION||'未获取'}} · 查询时间：{{evidence.toolEvidence?.queriedAt}}</p><h4>最近发布</h4><p v-for="r in evidence.toolEvidence?.recentReleases">{{r.VERSION_NO}} · {{r.STATUS}} · {{r.SUMMARY}}</p><h4>历史故障</h4><p v-for="i in evidence.toolEvidence?.similarIncidents">{{i.SYMPTOM}} → {{i.RESOLUTION}}</p><h4>SOP 引用</h4><p v-for="c in evidence.citations">{{c.title}} · {{c.versionNo}}</p></div></template></div></div></section></template>
