<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
const data=ref<any>({stats:{open:0,processing:0,resolved:0,occurrences:0},items:[]});
const selected=ref<any>(null); const loading=ref(true); const error=ref(''); const action=ref('');
const token=()=>sessionStorage.getItem('ops-token')||'';
async function api(path:string, options:RequestInit={}) { const r=await fetch('/api/admin/knowledge-gaps'+path,{...options,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json',...options.headers}}); const body=await r.json(); if(!r.ok) throw Error(body.message||'操作失败'); return body.data; }
async function load(){loading.value=true;try{data.value=await api('');if(selected.value)await open(selected.value.ID)}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function open(id:number){try{selected.value=await api('/'+id)}catch(e){error.value=e instanceof Error?e.message:'加载详情失败'}}
function note(label:string){return window.prompt(label)?.trim()||''}
async function processing(){const value=note('填写处理说明（必填）');if(!value||!selected.value)return;await run(()=>api('/'+selected.value.gap.ID+'/processing',{method:'PATCH',body:JSON.stringify({note:value})}));}
async function revalidate(){if(!selected.value)return;const value=window.prompt('可选：填写本次验证说明')||'';await run(async()=>{const result=await api('/'+selected.value.gap.ID+'/revalidate',{method:'POST',body:JSON.stringify({note:value})});await open(selected.value.gap.ID);alert(result.evidenceSufficient?'已找到当前已发布证据；请人工确认后关闭。':'仍未找到有效证据，缺口保持处理中。')})}
async function resolve(type:'VERIFIED_RESOLUTION'|'MANUAL_RESOLUTION'){const value=note(type==='VERIFIED_RESOLUTION'?'填写验证通过后的解决说明（必填）':'填写人工关闭原因（必填）');if(!value||!selected.value)return;await run(()=>api('/'+selected.value.gap.ID+'/resolve',{method:'PATCH',body:JSON.stringify({resolutionType:type,resolutionNote:value})}));}
async function run(work:()=>Promise<unknown>){action.value='busy';error.value='';try{await work();await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{action.value=''}}
const gap=computed(()=>selected.value?.gap);
onMounted(load);
</script>
<template><section><div class="assistant-head"><div><span class="eyebrow">KNOWLEDGE GAP RADAR</span><h1>知识缺口雷达</h1><p class="muted">从真实证据不足和用户点踩中建立可验证的知识治理闭环。</p></div></div>
<div class="gap-stats"><article><small>待处理</small><strong>{{data.stats.open}}</strong></article><article><small>处理中</small><strong>{{data.stats.processing}}</strong></article><article><small>已解决</small><strong>{{data.stats.resolved}}</strong></article><article><small>累计发生</small><strong>{{data.stats.occurrences}}</strong></article></div><p v-if="error" class="banner error">{{error}}</p>
<div class="gap-workspace"><section class="gap-list"><div class="list-caption"><b>缺口清单</b><span>按优先级、频次与最近发生排序</span></div><article v-for="g in data.items" :key="g.ID" class="gap-row" :class="{active:selected?.gap?.ID===g.ID}" @click="open(g.ID)"><div class="gap-rank">{{g.OCCURRENCE_COUNT}}</div><div><strong>{{g.SAMPLE_QUESTION}}</strong><small>{{g.KNOWLEDGE_BASE}} · {{g.SOURCE_TYPE}} · {{g.PRIORITY}} · 最近 {{new Date(g.LAST_SEEN_AT).toLocaleString()}}</small></div><span class="state-tag" :class="{ready:g.STATUS==='RESOLVED',processing:g.STATUS==='PROCESSING'}">{{g.STATUS}}</span></article><div v-if="!loading&&!data.items.length" class="empty"><div class="large-icon">⌁</div><h3>暂未发现知识缺口</h3><p>无证据拒答和点踩会在这里按问题聚合。</p></div></section>
<aside v-if="gap" class="gap-detail"><div class="detail-head"><div><small>{{gap.PRIORITY}} · {{gap.SOURCE_TYPE}}</small><h2>{{gap.SAMPLE_QUESTION}}</h2><p>{{gap.STATUS}} · 已发生 {{gap.OCCURRENCE_COUNT}} 次</p></div><button class="text-btn" @click="selected=null">关闭</button></div><p v-if="gap.PROCESSING_NOTE"><b>处理说明：</b>{{gap.PROCESSING_NOTE}}</p><p v-if="gap.RESOLUTION_NOTE"><b>解决说明：</b>{{gap.RESOLUTION_NOTE}}（{{gap.RESOLUTION_TYPE}}）</p><div class="gap-actions"><button v-if="gap.STATUS==='OPEN'" :disabled="!!action" @click="processing">标记处理中</button><template v-if="gap.STATUS==='PROCESSING'"><button :disabled="!!action" @click="revalidate">重新验证</button><button :disabled="!!action" class="outline" @click="resolve('VERIFIED_RESOLUTION')">验证通过后关闭</button><button :disabled="!!action" class="text-btn" @click="resolve('MANUAL_RESOLUTION')">人工关闭</button></template></div><section><h3>最近验证</h3><article v-for="v in selected.verifications" :key="v.ID" class="history"><b>{{v.RESULT}}</b><small>{{new Date(v.CREATED_AT).toLocaleString()}} · 操作人 {{v.OPERATOR_ID}}</small><p>{{v.RETRIEVAL_SUMMARY}}</p><p v-if="v.NOTES">{{v.NOTES}}</p></article><p v-if="!selected.verifications.length" class="muted">尚未重新验证。</p></section><section><h3>发生历史</h3><article v-for="o in selected.occurrences" :key="o.ID" class="history"><b>{{o.SOURCE_TYPE}}</b><small>{{new Date(o.CREATED_AT).toLocaleString()}} · 会话 {{o.CONVERSATION_ID??'已删除'}}</small><p>{{o.QUESTION}}</p><p>{{o.EVIDENCE_SUMMARY}}</p></article></section></aside></div></section></template>