CREATE TABLE IF NOT EXISTS app_user (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL, display_name VARCHAR(50) NOT NULL,
 role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS service_catalog (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, service_name VARCHAR(100) NOT NULL UNIQUE,
 display_name VARCHAR(100) NOT NULL, owner_name VARCHAR(50), current_version VARCHAR(30), runtime_status VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS knowledge_base (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(500),
 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS knowledge_document (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 kb_id BIGINT NOT NULL REFERENCES knowledge_base(id), title VARCHAR(200) NOT NULL,
 current_version_id BIGINT, created_by BIGINT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS document_version (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 document_id BIGINT NOT NULL REFERENCES knowledge_document(id),
 version_no VARCHAR(30) NOT NULL, original_name VARCHAR(255) NOT NULL,
 file_type VARCHAR(20) NOT NULL, file_size BIGINT NOT NULL,
 checksum VARCHAR(64) NOT NULL, storage_path VARCHAR(500) NOT NULL,
 process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 publish_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
 effective_at TIMESTAMP, chunk_count INT NOT NULL DEFAULT 0,
 failure_reason VARCHAR(1000), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 published_at TIMESTAMP, UNIQUE(document_id,version_no)
);
CREATE TABLE IF NOT EXISTS document_chunk_ref (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
 version_id BIGINT NOT NULL REFERENCES document_version(id),
 vector_id VARCHAR(100) NOT NULL UNIQUE, chunk_index INT NOT NULL,
 page_number INT, content LONGTEXT NOT NULL, UNIQUE(version_id,chunk_index)
);
CREATE TABLE IF NOT EXISTS app_seed (
 seed_key VARCHAR(100) PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS conversation (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,title VARCHAR(120) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS chat_message (id BIGINT AUTO_INCREMENT PRIMARY KEY,conversation_id BIGINT NOT NULL REFERENCES conversation(id),role VARCHAR(20) NOT NULL,content LONGTEXT NOT NULL,confidence_level VARCHAR(20),evidence_sufficiency VARCHAR(30),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS message_citation (id BIGINT AUTO_INCREMENT PRIMARY KEY,message_id BIGINT NOT NULL REFERENCES chat_message(id),version_id BIGINT NOT NULL,vector_id VARCHAR(100) NOT NULL,quote_text LONGTEXT NOT NULL,page_number INT,title VARCHAR(200),version_no VARCHAR(30));
CREATE TABLE IF NOT EXISTS release_record (id BIGINT AUTO_INCREMENT PRIMARY KEY,service_name VARCHAR(100) NOT NULL,version_no VARCHAR(30) NOT NULL,environment VARCHAR(30) NOT NULL,status VARCHAR(20) NOT NULL,released_at TIMESTAMP NOT NULL,summary VARCHAR(500));
CREATE TABLE IF NOT EXISTS incident_record (id BIGINT AUTO_INCREMENT PRIMARY KEY,service_name VARCHAR(100) NOT NULL,symptom VARCHAR(500) NOT NULL,root_cause VARCHAR(1000),resolution VARCHAR(1000),status VARCHAR(20) NOT NULL,occurred_at TIMESTAMP NOT NULL,resolved_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS diagnosis_record (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,kb_id BIGINT NOT NULL,service_name VARCHAR(100) NOT NULL,symptom VARCHAR(1000) NOT NULL,error_context LONGTEXT,result_content LONGTEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'OPEN',evidence_snapshot LONGTEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS knowledge_gap (id BIGINT AUTO_INCREMENT PRIMARY KEY,kb_id BIGINT NOT NULL,normalized_question VARCHAR(1000) NOT NULL,sample_question VARCHAR(1000) NOT NULL,occurrence_count INT NOT NULL DEFAULT 1,status VARCHAR(20) NOT NULL DEFAULT 'OPEN',first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at TIMESTAMP NULL,UNIQUE KEY uk_gap_question(kb_id,normalized_question(255)));
CREATE TABLE IF NOT EXISTS message_feedback (id BIGINT AUTO_INCREMENT PRIMARY KEY,message_id BIGINT NOT NULL REFERENCES chat_message(id),user_id BIGINT NOT NULL,rating VARCHAR(10) NOT NULL,comment_text VARCHAR(500),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_message_feedback(message_id,user_id));
CREATE TABLE IF NOT EXISTS tool_call_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY,user_id BIGINT NOT NULL,tool_name VARCHAR(80) NOT NULL,parameter_summary VARCHAR(500),result_count INT NOT NULL,success BOOLEAN NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sql_query_audit (id BIGINT AUTO_INCREMENT PRIMARY KEY,request_id VARCHAR(50) NOT NULL,user_id BIGINT NOT NULL,question VARCHAR(500) NOT NULL,generated_sql VARCHAR(4000),validation_status VARCHAR(20) NOT NULL,execution_status VARCHAR(20) NOT NULL,latency_ms BIGINT,row_count INT NOT NULL DEFAULT 0,failure_reason VARCHAR(1000),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS ai_call_log (id BIGINT AUTO_INCREMENT PRIMARY KEY,request_id VARCHAR(50) NOT NULL,user_id BIGINT NOT NULL,scene VARCHAR(40) NOT NULL,model_name VARCHAR(80),latency_ms BIGINT,input_tokens INT NOT NULL DEFAULT 0,output_tokens INT NOT NULL DEFAULT 0,token_estimated BOOLEAN NOT NULL DEFAULT TRUE,status VARCHAR(20) NOT NULL,error_code VARCHAR(50),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
